<?php

/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.0
 */

/**
 * Database `location`
 */

/* `location`.`areas` */
$areas = array(
  array('id' => '1', 'district_id' => '1', 'name' => 'Gulshan', 'bangla_name' => 'গুলশান'),
  array('id' => '2', 'district_id' => '1', 'name' => 'Banani', 'bangla_name' => 'বনানী'),
  array('id' => '3', 'district_id' => '1', 'name' => 'Dhanmondi', 'bangla_name' => 'ধানমন্ডি'),
  array('id' => '4', 'district_id' => '1', 'name' => 'Niketan', 'bangla_name' => 'নিকেতন'),
  array('id' => '5', 'district_id' => '14', 'name' => 'Debidwar', 'bangla_name' => 'দেবিদ্বার'),
  array('id' => '6', 'district_id' => '14', 'name' => 'Barura', 'bangla_name' => 'বরুড়া'),
  array('id' => '7', 'district_id' => '14', 'name' => 'Brahmanpara', 'bangla_name' => 'ব্রাহ্মণপাড়া'),
  array('id' => '8', 'district_id' => '14', 'name' => 'Chandina', 'bangla_name' => 'চান্দিনা'),
  array('id' => '9', 'district_id' => '14', 'name' => 'Chauddagram', 'bangla_name' => 'চৌদ্দগ্রাম'),
  array('id' => '10', 'district_id' => '14', 'name' => 'Daudkandi', 'bangla_name' => 'দাউদকান্দি'),
  array('id' => '11', 'district_id' => '14', 'name' => 'Homna', 'bangla_name' => 'হোমনা'),
  array('id' => '12', 'district_id' => '14', 'name' => 'Laksam', 'bangla_name' => 'লাকসাম'),
  array('id' => '13', 'district_id' => '14', 'name' => 'Muradnagar', 'bangla_name' => 'মুরাদনগর'),
  array('id' => '14', 'district_id' => '14', 'name' => 'Nangalkot', 'bangla_name' => 'নাঙ্গলকোট'),
  array('id' => '15', 'district_id' => '14', 'name' => 'Cumillasadar', 'bangla_name' => 'কুমিল্লা সদর'),
  array('id' => '16', 'district_id' => '14', 'name' => 'Meghna', 'bangla_name' => 'মেঘনা'),
  array('id' => '17', 'district_id' => '14', 'name' => 'Monohargonj', 'bangla_name' => 'মনোহরগঞ্জ'),
  array('id' => '18', 'district_id' => '14', 'name' => 'Sadarsouth', 'bangla_name' => 'সদর দক্ষিণ'),
  array('id' => '19', 'district_id' => '14', 'name' => 'Titas', 'bangla_name' => 'তিতাস'),
  array('id' => '20', 'district_id' => '14', 'name' => 'Burichang', 'bangla_name' => 'বুড়িচং'),
  array('id' => '21', 'district_id' => '14', 'name' => 'Lalmai', 'bangla_name' => 'লালমাই'),
  array('id' => '22', 'district_id' => '15', 'name' => 'Chhagalnaiya', 'bangla_name' => 'ছাগলনাইয়া'),
  array('id' => '23', 'district_id' => '15', 'name' => 'Sadar', 'bangla_name' => 'ফেনী সদর'),
  array('id' => '24', 'district_id' => '15', 'name' => 'Sonagazi', 'bangla_name' => 'সোনাগাজী'),
  array('id' => '25', 'district_id' => '15', 'name' => 'Fulgazi', 'bangla_name' => 'ফুলগাজী'),
  array('id' => '26', 'district_id' => '15', 'name' => 'Parshuram', 'bangla_name' => 'পরশুরাম'),
  array('id' => '27', 'district_id' => '15', 'name' => 'Daganbhuiyan', 'bangla_name' => 'দাগনভূঞা'),
  array('id' => '28', 'district_id' => '16', 'name' => 'Sadar', 'bangla_name' => 'ব্রাহ্মণবাড়িয়া সদর'),
  array('id' => '29', 'district_id' => '16', 'name' => 'Kasba', 'bangla_name' => 'কসবা'),
  array('id' => '30', 'district_id' => '16', 'name' => 'Nasirnagar', 'bangla_name' => 'নাসিরনগর'),
  array('id' => '31', 'district_id' => '16', 'name' => 'Sarail', 'bangla_name' => 'সরাইল'),
  array('id' => '32', 'district_id' => '16', 'name' => 'Ashuganj', 'bangla_name' => 'আশুগঞ্জ'),
  array('id' => '33', 'district_id' => '16', 'name' => 'Akhaura', 'bangla_name' => 'আখাউড়া'),
  array('id' => '34', 'district_id' => '16', 'name' => 'Nabinagar', 'bangla_name' => 'নবীনগর'),
  array('id' => '35', 'district_id' => '16', 'name' => 'Bancharampur', 'bangla_name' => 'বাঞ্ছারামপুর'),
  array('id' => '36', 'district_id' => '16', 'name' => 'Bijoynagar', 'bangla_name' => 'বিজয়নগর'),
  array('id' => '37', 'district_id' => '17', 'name' => 'Sadar', 'bangla_name' => 'রাঙ্গামাটি সদর'),
  array('id' => '38', 'district_id' => '17', 'name' => 'Kaptai', 'bangla_name' => 'কাপ্তাই'),
  array('id' => '39', 'district_id' => '17', 'name' => 'Kawkhali', 'bangla_name' => 'কাউখালী'),
  array('id' => '40', 'district_id' => '17', 'name' => 'Baghaichari', 'bangla_name' => 'বাঘাইছড়ি'),
  array('id' => '41', 'district_id' => '17', 'name' => 'Barkal', 'bangla_name' => 'বরকল'),
  array('id' => '42', 'district_id' => '17', 'name' => 'Langadu', 'bangla_name' => 'লংগদু'),
  array('id' => '43', 'district_id' => '17', 'name' => 'Rajasthali', 'bangla_name' => 'রাজস্থলী'),
  array('id' => '44', 'district_id' => '17', 'name' => 'Belaichari', 'bangla_name' => 'বিলাইছড়ি'),
  array('id' => '45', 'district_id' => '17', 'name' => 'Juraichari', 'bangla_name' => 'জুরাছড়ি'),
  array('id' => '46', 'district_id' => '17', 'name' => 'Naniarchar', 'bangla_name' => 'নানিয়ারচর'),
  array('id' => '47', 'district_id' => '18', 'name' => 'Sadar', 'bangla_name' => 'নোয়াখালী সদর'),
  array('id' => '48', 'district_id' => '18', 'name' => 'Companiganj', 'bangla_name' => 'কোম্পানীগঞ্জ'),
  array('id' => '49', 'district_id' => '18', 'name' => 'Begumganj', 'bangla_name' => 'বেগমগঞ্জ'),
  array('id' => '50', 'district_id' => '18', 'name' => 'Hatia', 'bangla_name' => 'হাতিয়া'),
  array('id' => '51', 'district_id' => '18', 'name' => 'Subarnachar', 'bangla_name' => 'সুবর্ণচর'),
  array('id' => '52', 'district_id' => '18', 'name' => 'Kabirhat', 'bangla_name' => 'কবিরহাট'),
  array('id' => '53', 'district_id' => '18', 'name' => 'Senbug', 'bangla_name' => 'সেনবাগ'),
  array('id' => '54', 'district_id' => '18', 'name' => 'Chatkhil', 'bangla_name' => 'চাটখিল'),
  array('id' => '55', 'district_id' => '18', 'name' => 'Sonaimuri', 'bangla_name' => 'সোনাইমুড়ী'),
  array('id' => '56', 'district_id' => '19', 'name' => 'Haimchar', 'bangla_name' => 'হাইমচর'),
  array('id' => '57', 'district_id' => '19', 'name' => 'Kachua', 'bangla_name' => 'কচুয়া'),
  array('id' => '58', 'district_id' => '19', 'name' => 'Shahrasti', 'bangla_name' => 'শাহরাস্তি'),
  array('id' => '59', 'district_id' => '19', 'name' => 'Sadar', 'bangla_name' => 'চাঁদপুর সদর'),
  array('id' => '60', 'district_id' => '19', 'name' => 'Matlabsouth', 'bangla_name' => 'দক্ষিণ মতলব'),
  array('id' => '61', 'district_id' => '19', 'name' => 'Hajiganj', 'bangla_name' => 'হাজীগঞ্জ'),
  array('id' => '62', 'district_id' => '19', 'name' => 'Matlabnorth', 'bangla_name' => 'উত্তর মতলব'),
  array('id' => '63', 'district_id' => '19', 'name' => 'Faridgonj', 'bangla_name' => 'ফরিদগঞ্জ'),
  array('id' => '64', 'district_id' => '20', 'name' => 'Sadar', 'bangla_name' => 'লক্ষ্মীপুর সদর'),
  array('id' => '65', 'district_id' => '20', 'name' => 'Kamalnagar', 'bangla_name' => 'কমলনগর'),
  array('id' => '66', 'district_id' => '20', 'name' => 'Raipur', 'bangla_name' => 'রায়পুর'),
  array('id' => '67', 'district_id' => '20', 'name' => 'Ramgati', 'bangla_name' => 'রামগতি'),
  array('id' => '68', 'district_id' => '20', 'name' => 'Ramganj', 'bangla_name' => 'রামগঞ্জ'),
  array('id' => '69', 'district_id' => '21', 'name' => 'Rangunia', 'bangla_name' => 'রাঙ্গুনিয়া'),
  array('id' => '70', 'district_id' => '21', 'name' => 'Sitakunda', 'bangla_name' => 'সীতাকুন্ড'),
  array('id' => '71', 'district_id' => '21', 'name' => 'Mirsharai', 'bangla_name' => 'মীরসরাই'),
  array('id' => '72', 'district_id' => '21', 'name' => 'Patiya', 'bangla_name' => 'পটিয়া'),
  array('id' => '73', 'district_id' => '21', 'name' => 'Sandwip', 'bangla_name' => 'সন্দ্বীপ'),
  array('id' => '74', 'district_id' => '21', 'name' => 'Banshkhali', 'bangla_name' => 'বাঁশখালী'),
  array('id' => '75', 'district_id' => '21', 'name' => 'Boalkhali', 'bangla_name' => 'বোয়ালখালী'),
  array('id' => '76', 'district_id' => '21', 'name' => 'Anwara', 'bangla_name' => 'আনোয়ারা'),
  array('id' => '77', 'district_id' => '21', 'name' => 'Chandanaish', 'bangla_name' => 'চন্দনাইশ'),
  array('id' => '78', 'district_id' => '21', 'name' => 'Satkania', 'bangla_name' => 'সাতকানিয়া'),
  array('id' => '79', 'district_id' => '21', 'name' => 'Lohagara', 'bangla_name' => 'লোহাগাড়া'),
  array('id' => '80', 'district_id' => '21', 'name' => 'Hathazari', 'bangla_name' => 'হাটহাজারী'),
  array('id' => '81', 'district_id' => '21', 'name' => 'Fatikchhari', 'bangla_name' => 'ফটিকছড়ি'),
  array('id' => '82', 'district_id' => '21', 'name' => 'Raozan', 'bangla_name' => 'রাউজান'),
  array('id' => '83', 'district_id' => '23', 'name' => 'Sadar', 'bangla_name' => 'খাগড়াছড়ি সদর'),
  array('id' => '84', 'district_id' => '23', 'name' => 'Dighinala', 'bangla_name' => 'দিঘীনালা'),
  array('id' => '85', 'district_id' => '23', 'name' => 'Panchari', 'bangla_name' => 'পানছড়ি'),
  array('id' => '86', 'district_id' => '23', 'name' => 'Laxmichhari', 'bangla_name' => 'লক্ষীছড়ি'),
  array('id' => '87', 'district_id' => '23', 'name' => 'Mohalchari', 'bangla_name' => 'মহালছড়ি'),
  array('id' => '88', 'district_id' => '23', 'name' => 'Manikchhari', 'bangla_name' => 'মানিকছড়ি'),
  array('id' => '89', 'district_id' => '23', 'name' => 'Ramgarh', 'bangla_name' => 'রামগড়'),
  array('id' => '90', 'district_id' => '23', 'name' => 'Matiranga', 'bangla_name' => 'মাটিরাঙ্গা'),
  array('id' => '91', 'district_id' => '23', 'name' => 'Guimara', 'bangla_name' => 'গুইমারা'),
  array('id' => '92', 'district_id' => '22', 'name' => 'Sadar', 'bangla_name' => 'কক্সবাজার সদর'),
  array('id' => '93', 'district_id' => '22', 'name' => 'Chakaria', 'bangla_name' => 'চকরিয়া'),
  array('id' => '94', 'district_id' => '22', 'name' => 'Kutubdia', 'bangla_name' => 'কুতুবদিয়া'),
  array('id' => '95', 'district_id' => '22', 'name' => 'Ukhiya', 'bangla_name' => 'উখিয়া'),
  array('id' => '96', 'district_id' => '22', 'name' => 'Moheshkhali', 'bangla_name' => 'মহেশখালী'),
  array('id' => '97', 'district_id' => '22', 'name' => 'Pekua', 'bangla_name' => 'পেকুয়া'),
  array('id' => '98', 'district_id' => '22', 'name' => 'Ramu', 'bangla_name' => 'রামু'),
  array('id' => '99', 'district_id' => '22', 'name' => 'Teknaf', 'bangla_name' => 'টেকনাফ'),
  array('id' => '100', 'district_id' => '24', 'name' => 'Sadar', 'bangla_name' => 'বান্দরবান সদর'),
  array('id' => '101', 'district_id' => '24', 'name' => 'Alikadam', 'bangla_name' => 'আলীকদম'),
  array('id' => '102', 'district_id' => '24', 'name' => 'Naikhongchhari', 'bangla_name' => 'নাইক্ষ্যংছড়ি'),
  array('id' => '103', 'district_id' => '24', 'name' => 'Rowangchhari', 'bangla_name' => 'রোয়াংছড়ি'),
  array('id' => '104', 'district_id' => '24', 'name' => 'Lama', 'bangla_name' => 'লামা'),
  array('id' => '105', 'district_id' => '24', 'name' => 'Ruma', 'bangla_name' => 'রুমা'),
  array('id' => '106', 'district_id' => '24', 'name' => 'Thanchi', 'bangla_name' => 'থানচি'),
  array('id' => '107', 'district_id' => '25', 'name' => 'Belkuchi', 'bangla_name' => 'বেলকুচি'),
  array('id' => '108', 'district_id' => '25', 'name' => 'Chauhali', 'bangla_name' => 'চৌহালি'),
  array('id' => '109', 'district_id' => '25', 'name' => 'Kamarkhand', 'bangla_name' => 'কামারখন্দ'),
  array('id' => '110', 'district_id' => '25', 'name' => 'Kazipur', 'bangla_name' => 'কাজীপুর'),
  array('id' => '111', 'district_id' => '25', 'name' => 'Raigonj', 'bangla_name' => 'রায়গঞ্জ'),
  array('id' => '112', 'district_id' => '25', 'name' => 'Shahjadpur', 'bangla_name' => 'শাহজাদপুর'),
  array('id' => '113', 'district_id' => '25', 'name' => 'Sirajganjsadar', 'bangla_name' => 'সিরাজগঞ্জ'),
  array('id' => '114', 'district_id' => '25', 'name' => 'Tarash', 'bangla_name' => 'তাড়াশ'),
  array('id' => '115', 'district_id' => '25', 'name' => 'Ullapara', 'bangla_name' => 'উল্লাপাড়া'),
  array('id' => '116', 'district_id' => '26', 'name' => 'Sujanagar', 'bangla_name' => 'সুজানগর'),
  array('id' => '117', 'district_id' => '26', 'name' => 'Ishurdi', 'bangla_name' => 'ঈশ্বরদী'),
  array('id' => '118', 'district_id' => '26', 'name' => 'Bhangura', 'bangla_name' => 'ভাঙ্গুড়া'),
  array('id' => '119', 'district_id' => '26', 'name' => 'Pabnasadar', 'bangla_name' => 'পাবনা সদর'),
  array('id' => '120', 'district_id' => '26', 'name' => 'Bera', 'bangla_name' => 'বেড়া'),
  array('id' => '121', 'district_id' => '26', 'name' => 'Atghoria', 'bangla_name' => 'আটঘরিয়া'),
  array('id' => '122', 'district_id' => '26', 'name' => 'Chatmohar', 'bangla_name' => 'চাটমোহর'),
  array('id' => '123', 'district_id' => '26', 'name' => 'Santhia', 'bangla_name' => 'সাঁথিয়া'),
  array('id' => '124', 'district_id' => '26', 'name' => 'Faridpur', 'bangla_name' => 'ফরিদপুর'),
  array('id' => '125', 'district_id' => '27', 'name' => 'Kahaloo', 'bangla_name' => 'কাহালু'),
  array('id' => '126', 'district_id' => '27', 'name' => 'Sadar', 'bangla_name' => 'বগুড়া সদর'),
  array('id' => '127', 'district_id' => '27', 'name' => 'Shariakandi', 'bangla_name' => 'সারিয়াকান্দি'),
  array('id' => '128', 'district_id' => '27', 'name' => 'Shajahanpur', 'bangla_name' => 'শাজাহানপুর'),
  array('id' => '129', 'district_id' => '27', 'name' => 'Dupchanchia', 'bangla_name' => 'দুপচাচিঁয়া'),
  array('id' => '130', 'district_id' => '27', 'name' => 'Adamdighi', 'bangla_name' => 'আদমদিঘি'),
  array('id' => '131', 'district_id' => '27', 'name' => 'Nondigram', 'bangla_name' => 'নন্দিগ্রাম'),
  array('id' => '132', 'district_id' => '27', 'name' => 'Sonatala', 'bangla_name' => 'সোনাতলা'),
  array('id' => '133', 'district_id' => '27', 'name' => 'Dhunot', 'bangla_name' => 'ধুনট'),
  array('id' => '134', 'district_id' => '27', 'name' => 'Gabtali', 'bangla_name' => 'গাবতলী'),
  array('id' => '135', 'district_id' => '27', 'name' => 'Sherpur', 'bangla_name' => 'শেরপুর'),
  array('id' => '136', 'district_id' => '27', 'name' => 'Shibganj', 'bangla_name' => 'শিবগঞ্জ'),
  array('id' => '137', 'district_id' => '28', 'name' => 'Paba', 'bangla_name' => 'পবা'),
  array('id' => '138', 'district_id' => '28', 'name' => 'Durgapur', 'bangla_name' => 'দুর্গাপুর'),
  array('id' => '139', 'district_id' => '28', 'name' => 'Mohonpur', 'bangla_name' => 'মোহনপুর'),
  array('id' => '140', 'district_id' => '28', 'name' => 'Charghat', 'bangla_name' => 'চারঘাট'),
  array('id' => '141', 'district_id' => '28', 'name' => 'Puthia', 'bangla_name' => 'পুঠিয়া'),
  array('id' => '142', 'district_id' => '28', 'name' => 'Bagha', 'bangla_name' => 'বাঘা'),
  array('id' => '143', 'district_id' => '28', 'name' => 'Godagari', 'bangla_name' => 'গোদাগাড়ী'),
  array('id' => '144', 'district_id' => '28', 'name' => 'Tanore', 'bangla_name' => 'তানোর'),
  array('id' => '145', 'district_id' => '28', 'name' => 'Bagmara', 'bangla_name' => 'বাগমারা'),
  array('id' => '146', 'district_id' => '29', 'name' => 'Natoresadar', 'bangla_name' => 'নাটোর সদর'),
  array('id' => '147', 'district_id' => '29', 'name' => 'Singra', 'bangla_name' => 'সিংড়া'),
  array('id' => '148', 'district_id' => '29', 'name' => 'Baraigram', 'bangla_name' => 'বড়াইগ্রাম'),
  array('id' => '149', 'district_id' => '29', 'name' => 'Bagatipara', 'bangla_name' => 'বাগাতিপাড়া'),
  array('id' => '150', 'district_id' => '29', 'name' => 'Lalpur', 'bangla_name' => 'লালপুর'),
  array('id' => '151', 'district_id' => '29', 'name' => 'Gurudaspur', 'bangla_name' => 'গুরুদাসপুর'),
  array('id' => '152', 'district_id' => '29', 'name' => 'Naldanga', 'bangla_name' => 'নলডাঙ্গা'),
  array('id' => '153', 'district_id' => '30', 'name' => 'Akkelpur', 'bangla_name' => 'আক্কেলপুর'),
  array('id' => '154', 'district_id' => '30', 'name' => 'Kalai', 'bangla_name' => 'কালাই'),
  array('id' => '155', 'district_id' => '30', 'name' => 'Khetlal', 'bangla_name' => 'ক্ষেতলাল'),
  array('id' => '156', 'district_id' => '30', 'name' => 'Panchbibi', 'bangla_name' => 'পাঁচবিবি'),
  array('id' => '157', 'district_id' => '30', 'name' => 'Joypurhatsadar', 'bangla_name' => 'জয়পুরহাট'),
  array('id' => '158', 'district_id' => '31', 'name' => 'Chapainawabganjsadar', 'bangla_name' => 'চাঁপাইনবাবগঞ্জ সদর'),
  array('id' => '159', 'district_id' => '31', 'name' => 'Gomostapur', 'bangla_name' => 'গোমস্তাপুর'),
  array('id' => '160', 'district_id' => '31', 'name' => 'Nachol', 'bangla_name' => 'নাচোল'),
  array('id' => '161', 'district_id' => '31', 'name' => 'Bholahat', 'bangla_name' => 'ভোলাহাট'),
  array('id' => '162', 'district_id' => '31', 'name' => 'Shibganj', 'bangla_name' => 'শিবগঞ্জ'),
  array('id' => '163', 'district_id' => '32', 'name' => 'Mohadevpur', 'bangla_name' => 'মহাদেবপুর'),
  array('id' => '164', 'district_id' => '32', 'name' => 'Badalgachi', 'bangla_name' => 'বদলগাছী'),
  array('id' => '165', 'district_id' => '32', 'name' => 'Patnitala', 'bangla_name' => 'পত্নিতলা'),
  array('id' => '166', 'district_id' => '32', 'name' => 'Dhamoirhat', 'bangla_name' => 'ধামইরহাট'),
  array('id' => '167', 'district_id' => '32', 'name' => 'Niamatpur', 'bangla_name' => 'নিয়ামতপুর'),
  array('id' => '168', 'district_id' => '32', 'name' => 'Manda', 'bangla_name' => 'মান্দা'),
  array('id' => '169', 'district_id' => '32', 'name' => 'Atrai', 'bangla_name' => 'আত্রাই'),
  array('id' => '170', 'district_id' => '32', 'name' => 'Raninagar', 'bangla_name' => 'রাণীনগর'),
  array('id' => '171', 'district_id' => '32', 'name' => 'Naogaonsadar', 'bangla_name' => 'নওগাঁ সদর'),
  array('id' => '172', 'district_id' => '32', 'name' => 'Porsha', 'bangla_name' => 'পোরশা'),
  array('id' => '173', 'district_id' => '32', 'name' => 'Sapahar', 'bangla_name' => 'সাপাহার'),
  array('id' => '174', 'district_id' => '33', 'name' => 'Manirampur', 'bangla_name' => 'মণিরামপুর'),
  array('id' => '175', 'district_id' => '33', 'name' => 'Abhaynagar', 'bangla_name' => 'অভয়নগর'),
  array('id' => '176', 'district_id' => '33', 'name' => 'Bagherpara', 'bangla_name' => 'বাঘারপাড়া'),
  array('id' => '177', 'district_id' => '33', 'name' => 'Chougachha', 'bangla_name' => 'চৌগাছা'),
  array('id' => '178', 'district_id' => '33', 'name' => 'Jhikargacha', 'bangla_name' => 'ঝিকরগাছা'),
  array('id' => '179', 'district_id' => '33', 'name' => 'Keshabpur', 'bangla_name' => 'কেশবপুর'),
  array('id' => '180', 'district_id' => '33', 'name' => 'Sadar', 'bangla_name' => 'যশোর সদর'),
  array('id' => '181', 'district_id' => '33', 'name' => 'Sharsha', 'bangla_name' => 'শার্শা'),
  array('id' => '182', 'district_id' => '34', 'name' => 'Assasuni', 'bangla_name' => 'আশাশুনি'),
  array('id' => '183', 'district_id' => '34', 'name' => 'Debhata', 'bangla_name' => 'দেবহাটা'),
  array('id' => '184', 'district_id' => '34', 'name' => 'Kalaroa', 'bangla_name' => 'কলারোয়া'),
  array('id' => '185', 'district_id' => '34', 'name' => 'Satkhirasadar', 'bangla_name' => 'সাতক্ষীরা সদর'),
  array('id' => '186', 'district_id' => '34', 'name' => 'Shyamnagar', 'bangla_name' => 'শ্যামনগর'),
  array('id' => '187', 'district_id' => '34', 'name' => 'Tala', 'bangla_name' => 'তালা'),
  array('id' => '188', 'district_id' => '34', 'name' => 'Kaliganj', 'bangla_name' => 'কালিগঞ্জ'),
  array('id' => '189', 'district_id' => '35', 'name' => 'Mujibnagar', 'bangla_name' => 'মুজিবনগর'),
  array('id' => '190', 'district_id' => '35', 'name' => 'Meherpursadar', 'bangla_name' => 'মেহেরপুর সদর'),
  array('id' => '191', 'district_id' => '35', 'name' => 'Gangni', 'bangla_name' => 'গাংনী'),
  array('id' => '192', 'district_id' => '36', 'name' => 'Narailsadar', 'bangla_name' => 'নড়াইল সদর'),
  array('id' => '193', 'district_id' => '36', 'name' => 'Lohagara', 'bangla_name' => 'লোহাগড়া'),
  array('id' => '194', 'district_id' => '36', 'name' => 'Kalia', 'bangla_name' => 'কালিয়া'),
  array('id' => '195', 'district_id' => '37', 'name' => 'Chuadangasadar', 'bangla_name' => 'চুয়াডাঙ্গা সদর'),
  array('id' => '196', 'district_id' => '37', 'name' => 'Alamdanga', 'bangla_name' => 'আলমডাঙ্গা'),
  array('id' => '197', 'district_id' => '37', 'name' => 'Damurhuda', 'bangla_name' => 'দামুড়হুদা'),
  array('id' => '198', 'district_id' => '37', 'name' => 'Jibannagar', 'bangla_name' => 'জীবননগর'),
  array('id' => '199', 'district_id' => '38', 'name' => 'Kushtiasadar', 'bangla_name' => 'কুষ্টিয়া সদর'),
  array('id' => '200', 'district_id' => '38', 'name' => 'Kumarkhali', 'bangla_name' => 'কুমারখালী'),
  array('id' => '201', 'district_id' => '38', 'name' => 'Khoksa', 'bangla_name' => 'খোকসা'),
  array('id' => '202', 'district_id' => '38', 'name' => 'Mirpur', 'bangla_name' => 'মিরপুর'),
  array('id' => '203', 'district_id' => '38', 'name' => 'Daulatpur', 'bangla_name' => 'দৌলতপুর'),
  array('id' => '204', 'district_id' => '38', 'name' => 'Bheramara', 'bangla_name' => 'ভেড়ামারা'),
  array('id' => '205', 'district_id' => '39', 'name' => 'Shalikha', 'bangla_name' => 'শালিখা'),
  array('id' => '206', 'district_id' => '39', 'name' => 'Sreepur', 'bangla_name' => 'শ্রীপুর'),
  array('id' => '207', 'district_id' => '39', 'name' => 'Magurasadar', 'bangla_name' => 'মাগুরা সদর'),
  array('id' => '208', 'district_id' => '39', 'name' => 'Mohammadpur', 'bangla_name' => 'মহম্মদপুর'),
  array('id' => '209', 'district_id' => '40', 'name' => 'Paikgasa', 'bangla_name' => 'পাইকগাছা'),
  array('id' => '210', 'district_id' => '40', 'name' => 'Fultola', 'bangla_name' => 'ফুলতলা'),
  array('id' => '211', 'district_id' => '40', 'name' => 'Digholia', 'bangla_name' => 'দিঘলিয়া'),
  array('id' => '212', 'district_id' => '40', 'name' => 'Rupsha', 'bangla_name' => 'রূপসা'),
  array('id' => '213', 'district_id' => '40', 'name' => 'Terokhada', 'bangla_name' => 'তেরখাদা'),
  array('id' => '214', 'district_id' => '40', 'name' => 'Dumuria', 'bangla_name' => 'ডুমুরিয়া'),
  array('id' => '215', 'district_id' => '40', 'name' => 'Botiaghata', 'bangla_name' => 'বটিয়াঘাটা'),
  array('id' => '216', 'district_id' => '40', 'name' => 'Dakop', 'bangla_name' => 'দাকোপ'),
  array('id' => '217', 'district_id' => '40', 'name' => 'Koyra', 'bangla_name' => 'কয়রা'),
  array('id' => '218', 'district_id' => '41', 'name' => 'Fakirhat', 'bangla_name' => 'ফকিরহাট'),
  array('id' => '219', 'district_id' => '41', 'name' => 'Sadar', 'bangla_name' => 'বাগেরহাট সদর'),
  array('id' => '220', 'district_id' => '41', 'name' => 'Mollahat', 'bangla_name' => 'মোল্লাহাট'),
  array('id' => '221', 'district_id' => '41', 'name' => 'Sarankhola', 'bangla_name' => 'শরণখোলা'),
  array('id' => '222', 'district_id' => '41', 'name' => 'Rampal', 'bangla_name' => 'রামপাল'),
  array('id' => '223', 'district_id' => '41', 'name' => 'Morrelganj', 'bangla_name' => 'মোড়েলগঞ্জ'),
  array('id' => '224', 'district_id' => '41', 'name' => 'Kachua', 'bangla_name' => 'কচুয়া'),
  array('id' => '225', 'district_id' => '41', 'name' => 'Mongla', 'bangla_name' => 'মোংলা'),
  array('id' => '226', 'district_id' => '41', 'name' => 'Chitalmari', 'bangla_name' => 'চিতলমারী'),
  array('id' => '227', 'district_id' => '42', 'name' => 'Sadar', 'bangla_name' => 'ঝিনাইদহ সদর'),
  array('id' => '228', 'district_id' => '42', 'name' => 'Shailkupa', 'bangla_name' => 'শৈলকুপা'),
  array('id' => '229', 'district_id' => '42', 'name' => 'Harinakundu', 'bangla_name' => 'হরিণাকুন্ডু'),
  array('id' => '230', 'district_id' => '42', 'name' => 'Kaliganj', 'bangla_name' => 'কালীগঞ্জ'),
  array('id' => '231', 'district_id' => '42', 'name' => 'Kotchandpur', 'bangla_name' => 'কোটচাঁদপুর'),
  array('id' => '232', 'district_id' => '42', 'name' => 'Moheshpur', 'bangla_name' => 'মহেশপুর'),
  array('id' => '233', 'district_id' => '43', 'name' => 'Sadar', 'bangla_name' => 'ঝালকাঠি সদর'),
  array('id' => '234', 'district_id' => '43', 'name' => 'Kathalia', 'bangla_name' => 'কাঠালিয়া'),
  array('id' => '235', 'district_id' => '43', 'name' => 'Nalchity', 'bangla_name' => 'নলছিটি'),
  array('id' => '236', 'district_id' => '43', 'name' => 'Rajapur', 'bangla_name' => 'রাজাপুর'),
  array('id' => '237', 'district_id' => '44', 'name' => 'Bauphal', 'bangla_name' => 'বাউফল'),
  array('id' => '238', 'district_id' => '44', 'name' => 'Sadar', 'bangla_name' => 'পটুয়াখালী সদর'),
  array('id' => '239', 'district_id' => '44', 'name' => 'Dumki', 'bangla_name' => 'দুমকি'),
  array('id' => '240', 'district_id' => '44', 'name' => 'Dashmina', 'bangla_name' => 'দশমিনা'),
  array('id' => '241', 'district_id' => '44', 'name' => 'Kalapara', 'bangla_name' => 'কলাপাড়া'),
  array('id' => '242', 'district_id' => '44', 'name' => 'Mirzaganj', 'bangla_name' => 'মির্জাগঞ্জ'),
  array('id' => '243', 'district_id' => '44', 'name' => 'Galachipa', 'bangla_name' => 'গলাচিপা'),
  array('id' => '244', 'district_id' => '44', 'name' => 'Rangabali', 'bangla_name' => 'রাঙ্গাবালী'),
  array('id' => '245', 'district_id' => '45', 'name' => 'Sadar', 'bangla_name' => 'পিরোজপুর সদর'),
  array('id' => '246', 'district_id' => '45', 'name' => 'Nazirpur', 'bangla_name' => 'নাজিরপুর'),
  array('id' => '247', 'district_id' => '45', 'name' => 'Kawkhali', 'bangla_name' => 'কাউখালী'),
  array('id' => '248', 'district_id' => '45', 'name' => 'Bhandaria', 'bangla_name' => 'ভান্ডারিয়া'),
  array('id' => '249', 'district_id' => '45', 'name' => 'Mathbaria', 'bangla_name' => 'মঠবাড়ীয়া'),
  array('id' => '250', 'district_id' => '45', 'name' => 'Nesarabad', 'bangla_name' => 'নেছারাবাদ'),
  array('id' => '251', 'district_id' => '45', 'name' => 'Indurkani', 'bangla_name' => 'ইন্দুরকানী'),
  array('id' => '252', 'district_id' => '46', 'name' => 'Barishalsadar', 'bangla_name' => 'বরিশাল সদর'),
  array('id' => '253', 'district_id' => '46', 'name' => 'Bakerganj', 'bangla_name' => 'বাকেরগঞ্জ'),
  array('id' => '254', 'district_id' => '46', 'name' => 'Babuganj', 'bangla_name' => 'বাবুগঞ্জ'),
  array('id' => '255', 'district_id' => '46', 'name' => 'Wazirpur', 'bangla_name' => 'উজিরপুর'),
  array('id' => '256', 'district_id' => '46', 'name' => 'Banaripara', 'bangla_name' => 'বানারীপাড়া'),
  array('id' => '257', 'district_id' => '46', 'name' => 'Gournadi', 'bangla_name' => 'গৌরনদী'),
  array('id' => '258', 'district_id' => '46', 'name' => 'Agailjhara', 'bangla_name' => 'আগৈলঝাড়া'),
  array('id' => '259', 'district_id' => '46', 'name' => 'Mehendiganj', 'bangla_name' => 'মেহেন্দিগঞ্জ'),
  array('id' => '260', 'district_id' => '46', 'name' => 'Muladi', 'bangla_name' => 'মুলাদী'),
  array('id' => '261', 'district_id' => '46', 'name' => 'Hizla', 'bangla_name' => 'হিজলা'),
  array('id' => '262', 'district_id' => '47', 'name' => 'Sadar', 'bangla_name' => 'ভোলা সদর'),
  array('id' => '263', 'district_id' => '47', 'name' => 'Borhanuddin', 'bangla_name' => 'বোরহান উদ্দিন'),
  array('id' => '264', 'district_id' => '47', 'name' => 'Charfesson', 'bangla_name' => 'চরফ্যাশন'),
  array('id' => '265', 'district_id' => '47', 'name' => 'Doulatkhan', 'bangla_name' => 'দৌলতখান'),
  array('id' => '266', 'district_id' => '47', 'name' => 'Monpura', 'bangla_name' => 'মনপুরা'),
  array('id' => '267', 'district_id' => '47', 'name' => 'Tazumuddin', 'bangla_name' => 'তজুমদ্দিন'),
  array('id' => '268', 'district_id' => '47', 'name' => 'Lalmohan', 'bangla_name' => 'লালমোহন'),
  array('id' => '269', 'district_id' => '48', 'name' => 'Amtali', 'bangla_name' => 'আমতলী'),
  array('id' => '270', 'district_id' => '48', 'name' => 'Sadar', 'bangla_name' => 'বরগুনা সদর'),
  array('id' => '271', 'district_id' => '48', 'name' => 'Betagi', 'bangla_name' => 'বেতাগী'),
  array('id' => '272', 'district_id' => '48', 'name' => 'Bamna', 'bangla_name' => 'বামনা'),
  array('id' => '273', 'district_id' => '48', 'name' => 'Pathorghata', 'bangla_name' => 'পাথরঘাটা'),
  array('id' => '274', 'district_id' => '48', 'name' => 'Taltali', 'bangla_name' => 'তালতলি'),
  array('id' => '275', 'district_id' => '49', 'name' => 'Balaganj', 'bangla_name' => 'বালাগঞ্জ'),
  array('id' => '276', 'district_id' => '49', 'name' => 'Beanibazar', 'bangla_name' => 'বিয়ানীবাজার'),
  array('id' => '277', 'district_id' => '49', 'name' => 'Bishwanath', 'bangla_name' => 'বিশ্বনাথ'),
  array('id' => '278', 'district_id' => '49', 'name' => 'Companiganj', 'bangla_name' => 'কোম্পানীগঞ্জ'),
  array('id' => '279', 'district_id' => '49', 'name' => 'Fenchuganj', 'bangla_name' => 'ফেঞ্চুগঞ্জ'),
  array('id' => '280', 'district_id' => '49', 'name' => 'Golapganj', 'bangla_name' => 'গোলাপগঞ্জ'),
  array('id' => '281', 'district_id' => '49', 'name' => 'Gowainghat', 'bangla_name' => 'গোয়াইনঘাট'),
  array('id' => '282', 'district_id' => '49', 'name' => 'Jaintiapur', 'bangla_name' => 'জৈন্তাপুর'),
  array('id' => '283', 'district_id' => '49', 'name' => 'Kanaighat', 'bangla_name' => 'কানাইঘাট'),
  array('id' => '284', 'district_id' => '49', 'name' => 'Sylhetsadar', 'bangla_name' => 'সিলেট সদর'),
  array('id' => '285', 'district_id' => '49', 'name' => 'Zakiganj', 'bangla_name' => 'জকিগঞ্জ'),
  array('id' => '286', 'district_id' => '49', 'name' => 'Dakshinsurma', 'bangla_name' => 'দক্ষিণ সুরমা'),
  array('id' => '287', 'district_id' => '49', 'name' => 'Osmaninagar', 'bangla_name' => 'ওসমানীনগর'),
  array('id' => '288', 'district_id' => '50', 'name' => 'Barlekha', 'bangla_name' => 'বড়লেখা'),
  array('id' => '289', 'district_id' => '50', 'name' => 'Kamolganj', 'bangla_name' => 'কমলগঞ্জ'),
  array('id' => '290', 'district_id' => '50', 'name' => 'Kulaura', 'bangla_name' => 'কুলাউড়া'),
  array('id' => '291', 'district_id' => '50', 'name' => 'Moulvibazarsadar', 'bangla_name' => 'মৌলভীবাজার সদর'),
  array('id' => '292', 'district_id' => '50', 'name' => 'Rajnagar', 'bangla_name' => 'রাজনগর'),
  array('id' => '293', 'district_id' => '50', 'name' => 'Sreemangal', 'bangla_name' => 'শ্রীমঙ্গল'),
  array('id' => '294', 'district_id' => '50', 'name' => 'Juri', 'bangla_name' => 'জুড়ী'),
  array('id' => '295', 'district_id' => '51', 'name' => 'Nabiganj', 'bangla_name' => 'নবীগঞ্জ'),
  array('id' => '296', 'district_id' => '51', 'name' => 'Bahubal', 'bangla_name' => 'বাহুবল'),
  array('id' => '297', 'district_id' => '51', 'name' => 'Ajmiriganj', 'bangla_name' => 'আজমিরীগঞ্জ'),
  array('id' => '298', 'district_id' => '51', 'name' => 'Baniachong', 'bangla_name' => 'বানিয়াচং'),
  array('id' => '299', 'district_id' => '51', 'name' => 'Lakhai', 'bangla_name' => 'লাখাই'),
  array('id' => '300', 'district_id' => '51', 'name' => 'Chunarughat', 'bangla_name' => 'চুনারুঘাট'),
  array('id' => '301', 'district_id' => '51', 'name' => 'Habiganjsadar', 'bangla_name' => 'হবিগঞ্জ সদর'),
  array('id' => '302', 'district_id' => '51', 'name' => 'Madhabpur', 'bangla_name' => 'মাধবপুর'),
  array('id' => '303', 'district_id' => '51', 'name' => 'Shayestaganj', 'bangla_name' => 'শায়েস্তাগঞ্জ'),
  array('id' => '304', 'district_id' => '52', 'name' => 'Sadar', 'bangla_name' => 'সুনামগঞ্জ সদর'),
  array('id' => '305', 'district_id' => '52', 'name' => 'Southsunamganj', 'bangla_name' => 'দক্ষিণ সুনামগঞ্জ'),
  array('id' => '306', 'district_id' => '52', 'name' => 'Bishwambarpur', 'bangla_name' => 'বিশ্বম্ভরপুর'),
  array('id' => '307', 'district_id' => '52', 'name' => 'Chhatak', 'bangla_name' => 'ছাতক'),
  array('id' => '308', 'district_id' => '52', 'name' => 'Jagannathpur', 'bangla_name' => 'জগন্নাথপুর'),
  array('id' => '309', 'district_id' => '52', 'name' => 'Dowarabazar', 'bangla_name' => 'দোয়ারাবাজার'),
  array('id' => '310', 'district_id' => '52', 'name' => 'Tahirpur,', 'bangla_name' => 'তাহিরপুর'),
  array('id' => '311', 'district_id' => '52', 'name' => 'Dharmapasha', 'bangla_name' => 'ধর্মপাশা'),
  array('id' => '312', 'district_id' => '52', 'name' => 'Jamalganj', 'bangla_name' => 'জামালগঞ্জ'),
  array('id' => '313', 'district_id' => '52', 'name' => 'Shalla', 'bangla_name' => 'শাল্লা'),
  array('id' => '314', 'district_id' => '52', 'name' => 'Derai', 'bangla_name' => 'দিরাই'),
  array('id' => '315', 'district_id' => '3', 'name' => 'Belabo', 'bangla_name' => 'বেলাবো'),
  array('id' => '316', 'district_id' => '3', 'name' => 'Monohardi', 'bangla_name' => 'মনোহরদী'),
  array('id' => '317', 'district_id' => '3', 'name' => 'Narsingdisadar', 'bangla_name' => 'নরসিংদী'),
  array('id' => '318', 'district_id' => '3', 'name' => 'Palash', 'bangla_name' => 'পলাশ'),
  array('id' => '319', 'district_id' => '3', 'name' => 'Raipura', 'bangla_name' => 'রায়পুরা'),
  array('id' => '320', 'district_id' => '3', 'name' => 'Shibpur', 'bangla_name' => 'শিবপুর'),
  array('id' => '321', 'district_id' => '4', 'name' => 'Kaliganj', 'bangla_name' => 'কালীগঞ্জ'),
  array('id' => '322', 'district_id' => '4', 'name' => 'Kaliakair', 'bangla_name' => 'কালিয়াকৈর'),
  array('id' => '323', 'district_id' => '4', 'name' => 'Kapasia', 'bangla_name' => 'কাপাসিয়া'),
  array('id' => '324', 'district_id' => '4', 'name' => 'Sadar', 'bangla_name' => 'গাজীপুর সদর'),
  array('id' => '325', 'district_id' => '4', 'name' => 'Sreepur', 'bangla_name' => 'শ্রীপুর'),
  array('id' => '326', 'district_id' => '5', 'name' => 'Sadar', 'bangla_name' => 'শরিয়তপুর সদর'),
  array('id' => '327', 'district_id' => '5', 'name' => 'Naria', 'bangla_name' => 'নড়িয়া'),
  array('id' => '328', 'district_id' => '5', 'name' => 'Zajira', 'bangla_name' => 'জাজিরা'),
  array('id' => '329', 'district_id' => '5', 'name' => 'Gosairhat', 'bangla_name' => 'গোসাইরহাট'),
  array('id' => '330', 'district_id' => '5', 'name' => 'Bhedarganj', 'bangla_name' => 'ভেদরগঞ্জ'),
  array('id' => '331', 'district_id' => '5', 'name' => 'Damudya', 'bangla_name' => 'ডামুড্যা'),
  array('id' => '332', 'district_id' => '6', 'name' => 'Araihazar', 'bangla_name' => 'আড়াইহাজার'),
  array('id' => '333', 'district_id' => '6', 'name' => 'Bandar', 'bangla_name' => 'বন্দর'),
  array('id' => '334', 'district_id' => '6', 'name' => 'Narayanganjsadar', 'bangla_name' => 'নারায়নগঞ্জ সদর'),
  array('id' => '335', 'district_id' => '6', 'name' => 'Rupganj', 'bangla_name' => 'রূপগঞ্জ'),
  array('id' => '336', 'district_id' => '6', 'name' => 'Sonargaon', 'bangla_name' => 'সোনারগাঁ'),
  array('id' => '337', 'district_id' => '7', 'name' => 'Basail', 'bangla_name' => 'বাসাইল'),
  array('id' => '338', 'district_id' => '7', 'name' => 'Bhuapur', 'bangla_name' => 'ভুয়াপুর'),
  array('id' => '339', 'district_id' => '7', 'name' => 'Delduar', 'bangla_name' => 'দেলদুয়ার'),
  array('id' => '340', 'district_id' => '7', 'name' => 'Ghatail', 'bangla_name' => 'ঘাটাইল'),
  array('id' => '341', 'district_id' => '7', 'name' => 'Gopalpur', 'bangla_name' => 'গোপালপুর'),
  array('id' => '342', 'district_id' => '7', 'name' => 'Madhupur', 'bangla_name' => 'মধুপুর'),
  array('id' => '343', 'district_id' => '7', 'name' => 'Mirzapur', 'bangla_name' => 'মির্জাপুর'),
  array('id' => '344', 'district_id' => '7', 'name' => 'Nagarpur', 'bangla_name' => 'নাগরপুর'),
  array('id' => '345', 'district_id' => '7', 'name' => 'Sakhipur', 'bangla_name' => 'সখিপুর'),
  array('id' => '346', 'district_id' => '7', 'name' => 'Tangailsadar', 'bangla_name' => 'টাঙ্গাইল সদর'),
  array('id' => '347', 'district_id' => '7', 'name' => 'Kalihati', 'bangla_name' => 'কালিহাতী'),
  array('id' => '348', 'district_id' => '7', 'name' => 'Dhanbari', 'bangla_name' => 'ধনবাড়ী'),
  array('id' => '349', 'district_id' => '8', 'name' => 'Itna', 'bangla_name' => 'ইটনা'),
  array('id' => '350', 'district_id' => '8', 'name' => 'Katiadi', 'bangla_name' => 'কটিয়াদী'),
  array('id' => '351', 'district_id' => '8', 'name' => 'Bhairab', 'bangla_name' => 'ভৈরব'),
  array('id' => '352', 'district_id' => '8', 'name' => 'Tarail', 'bangla_name' => 'তাড়াইল'),
  array('id' => '353', 'district_id' => '8', 'name' => 'Hossainpur', 'bangla_name' => 'হোসেনপুর'),
  array('id' => '354', 'district_id' => '8', 'name' => 'Pakundia', 'bangla_name' => 'পাকুন্দিয়া'),
  array('id' => '355', 'district_id' => '8', 'name' => 'Kuliarchar', 'bangla_name' => 'কুলিয়ারচর'),
  array('id' => '356', 'district_id' => '8', 'name' => 'Kishoreganjsadar', 'bangla_name' => 'কিশোরগঞ্জ সদর'),
  array('id' => '357', 'district_id' => '8', 'name' => 'Karimgonj', 'bangla_name' => 'করিমগঞ্জ'),
  array('id' => '358', 'district_id' => '8', 'name' => 'Bajitpur', 'bangla_name' => 'বাজিতপুর'),
  array('id' => '359', 'district_id' => '8', 'name' => 'Austagram', 'bangla_name' => 'অষ্টগ্রাম'),
  array('id' => '360', 'district_id' => '8', 'name' => 'Mithamoin', 'bangla_name' => 'মিঠামইন'),
  array('id' => '361', 'district_id' => '8', 'name' => 'Nikli', 'bangla_name' => 'নিকলী'),
  array('id' => '362', 'district_id' => '2', 'name' => 'Harirampur', 'bangla_name' => 'হরিরামপুর'),
  array('id' => '363', 'district_id' => '2', 'name' => 'Saturia', 'bangla_name' => 'সাটুরিয়া'),
  array('id' => '364', 'district_id' => '2', 'name' => 'Sadar', 'bangla_name' => 'মানিকগঞ্জ সদর'),
  array('id' => '365', 'district_id' => '2', 'name' => 'Gior', 'bangla_name' => 'ঘিওর'),
  array('id' => '366', 'district_id' => '2', 'name' => 'Shibaloy', 'bangla_name' => 'শিবালয়'),
  array('id' => '367', 'district_id' => '2', 'name' => 'Doulatpur', 'bangla_name' => 'দৌলতপুর'),
  array('id' => '368', 'district_id' => '2', 'name' => 'Singiar', 'bangla_name' => 'সিংগাইর'),
  array('id' => '369', 'district_id' => '1', 'name' => 'Savar', 'bangla_name' => 'সাভার'),
  array('id' => '370', 'district_id' => '1', 'name' => 'Dhamrai', 'bangla_name' => 'ধামরাই'),
  array('id' => '371', 'district_id' => '1', 'name' => 'Keraniganj', 'bangla_name' => 'কেরাণীগঞ্জ'),
  array('id' => '372', 'district_id' => '1', 'name' => 'Nawabganj', 'bangla_name' => 'নবাবগঞ্জ'),
  array('id' => '373', 'district_id' => '1', 'name' => 'Dohar', 'bangla_name' => 'দোহার'),
  array('id' => '374', 'district_id' => '9', 'name' => 'Sadar', 'bangla_name' => 'মুন্সিগঞ্জ সদর'),
  array('id' => '375', 'district_id' => '9', 'name' => 'Sreenagar', 'bangla_name' => 'শ্রীনগর'),
  array('id' => '376', 'district_id' => '9', 'name' => 'Sirajdikhan', 'bangla_name' => 'সিরাজদিখান'),
  array('id' => '377', 'district_id' => '9', 'name' => 'Louhajanj', 'bangla_name' => 'লৌহজং'),
  array('id' => '378', 'district_id' => '9', 'name' => 'Gajaria', 'bangla_name' => 'গজারিয়া'),
  array('id' => '379', 'district_id' => '9', 'name' => 'Tongibari', 'bangla_name' => 'টংগীবাড়ি'),
  array('id' => '380', 'district_id' => '10', 'name' => 'Sadar', 'bangla_name' => 'রাজবাড়ী সদর'),
  array('id' => '381', 'district_id' => '10', 'name' => 'Goalanda', 'bangla_name' => 'গোয়ালন্দ'),
  array('id' => '382', 'district_id' => '10', 'name' => 'Pangsa', 'bangla_name' => 'পাংশা'),
  array('id' => '383', 'district_id' => '10', 'name' => 'Baliakandi', 'bangla_name' => 'বালিয়াকান্দি'),
  array('id' => '384', 'district_id' => '10', 'name' => 'Kalukhali', 'bangla_name' => 'কালুখালী'),
  array('id' => '385', 'district_id' => '11', 'name' => 'Sadar', 'bangla_name' => 'মাদারীপুর সদর'),
  array('id' => '386', 'district_id' => '11', 'name' => 'Shibchar', 'bangla_name' => 'শিবচর'),
  array('id' => '387', 'district_id' => '11', 'name' => 'Kalkini', 'bangla_name' => 'কালকিনি'),
  array('id' => '388', 'district_id' => '11', 'name' => 'Rajoir', 'bangla_name' => 'রাজৈর'),
  array('id' => '389', 'district_id' => '12', 'name' => 'Sadar', 'bangla_name' => 'গোপালগঞ্জ সদর'),
  array('id' => '390', 'district_id' => '12', 'name' => 'Kashiani', 'bangla_name' => 'কাশিয়ানী'),
  array('id' => '391', 'district_id' => '12', 'name' => 'Tungipara', 'bangla_name' => 'টুংগীপাড়া'),
  array('id' => '392', 'district_id' => '12', 'name' => 'Kotalipara', 'bangla_name' => 'কোটালীপাড়া'),
  array('id' => '393', 'district_id' => '12', 'name' => 'Muksudpur', 'bangla_name' => 'মুকসুদপুর'),
  array('id' => '394', 'district_id' => '13', 'name' => 'Sadar', 'bangla_name' => 'ফরিদপুর সদর'),
  array('id' => '395', 'district_id' => '13', 'name' => 'Alfadanga', 'bangla_name' => 'আলফাডাঙ্গা'),
  array('id' => '396', 'district_id' => '13', 'name' => 'Boalmari', 'bangla_name' => 'বোয়ালমারী'),
  array('id' => '397', 'district_id' => '13', 'name' => 'Sadarpur', 'bangla_name' => 'সদরপুর'),
  array('id' => '398', 'district_id' => '13', 'name' => 'Nagarkanda', 'bangla_name' => 'নগরকান্দা'),
  array('id' => '399', 'district_id' => '13', 'name' => 'Bhanga', 'bangla_name' => 'ভাঙ্গা'),
  array('id' => '400', 'district_id' => '13', 'name' => 'Charbhadrasan', 'bangla_name' => 'চরভদ্রাসন'),
  array('id' => '401', 'district_id' => '13', 'name' => 'Madhukhali', 'bangla_name' => 'মধুখালী'),
  array('id' => '402', 'district_id' => '13', 'name' => 'Saltha', 'bangla_name' => 'সালথা'),
  array('id' => '403', 'district_id' => '53', 'name' => 'Panchagarhsadar', 'bangla_name' => 'পঞ্চগড়'),
  array('id' => '404', 'district_id' => '53', 'name' => 'Debiganj', 'bangla_name' => 'দেবীগঞ্জ'),
  array('id' => '405', 'district_id' => '53', 'name' => 'Boda', 'bangla_name' => 'বোদা'),
  array('id' => '406', 'district_id' => '53', 'name' => 'Atwari', 'bangla_name' => 'আটোয়ারী'),
  array('id' => '407', 'district_id' => '53', 'name' => 'Tetulia', 'bangla_name' => 'তেতুলিয়া'),
  array('id' => '408', 'district_id' => '54', 'name' => 'Nawabganj', 'bangla_name' => 'নবাবগঞ্জ'),
  array('id' => '409', 'district_id' => '54', 'name' => 'Birganj', 'bangla_name' => 'বীরগঞ্জ'),
  array('id' => '410', 'district_id' => '54', 'name' => 'Ghoraghat', 'bangla_name' => 'ঘোড়াঘাট'),
  array('id' => '411', 'district_id' => '54', 'name' => 'Birampur', 'bangla_name' => 'বিরামপুর'),
  array('id' => '412', 'district_id' => '54', 'name' => 'Parbatipur', 'bangla_name' => 'পার্বতীপুর'),
  array('id' => '413', 'district_id' => '54', 'name' => 'Bochaganj', 'bangla_name' => 'বোচাগঞ্জ'),
  array('id' => '414', 'district_id' => '54', 'name' => 'Kaharol', 'bangla_name' => 'কাহারোল'),
  array('id' => '415', 'district_id' => '54', 'name' => 'Fulbari', 'bangla_name' => 'ফুলবাড়ী'),
  array('id' => '416', 'district_id' => '54', 'name' => 'Dinajpursadar', 'bangla_name' => 'দিনাজপুর সদর'),
  array('id' => '417', 'district_id' => '54', 'name' => 'Hakimpur', 'bangla_name' => 'হাকিমপুর'),
  array('id' => '418', 'district_id' => '54', 'name' => 'Khansama', 'bangla_name' => 'খানসামা'),
  array('id' => '419', 'district_id' => '54', 'name' => 'Birol', 'bangla_name' => 'বিরল'),
  array('id' => '420', 'district_id' => '54', 'name' => 'Chirirbandar', 'bangla_name' => 'চিরিরবন্দর'),
  array('id' => '421', 'district_id' => '55', 'name' => 'Sadar', 'bangla_name' => 'লালমনিরহাট সদর'),
  array('id' => '422', 'district_id' => '55', 'name' => 'Kaliganj', 'bangla_name' => 'কালীগঞ্জ'),
  array('id' => '423', 'district_id' => '55', 'name' => 'Hatibandha', 'bangla_name' => 'হাতীবান্ধা'),
  array('id' => '424', 'district_id' => '55', 'name' => 'Patgram', 'bangla_name' => 'পাটগ্রাম'),
  array('id' => '425', 'district_id' => '55', 'name' => 'Aditmari', 'bangla_name' => 'আদিতমারী'),
  array('id' => '426', 'district_id' => '56', 'name' => 'Syedpur', 'bangla_name' => 'সৈয়দপুর'),
  array('id' => '427', 'district_id' => '56', 'name' => 'Domar', 'bangla_name' => 'ডোমার'),
  array('id' => '428', 'district_id' => '56', 'name' => 'Dimla', 'bangla_name' => 'ডিমলা'),
  array('id' => '429', 'district_id' => '56', 'name' => 'Jaldhaka', 'bangla_name' => 'জলঢাকা'),
  array('id' => '430', 'district_id' => '56', 'name' => 'Kishorganj', 'bangla_name' => 'কিশোরগঞ্জ'),
  array('id' => '431', 'district_id' => '56', 'name' => 'Nilphamarisadar', 'bangla_name' => 'নীলফামারী সদর'),
  array('id' => '432', 'district_id' => '57', 'name' => 'Sadullapur', 'bangla_name' => 'সাদুল্লাপুর'),
  array('id' => '433', 'district_id' => '57', 'name' => 'Gaibandhasadar', 'bangla_name' => 'গাইবান্ধা সদর'),
  array('id' => '434', 'district_id' => '57', 'name' => 'Palashbari', 'bangla_name' => 'পলাশবাড়ী'),
  array('id' => '435', 'district_id' => '57', 'name' => 'Saghata', 'bangla_name' => 'সাঘাটা'),
  array('id' => '436', 'district_id' => '57', 'name' => 'Gobindaganj', 'bangla_name' => 'গোবিন্দগঞ্জ'),
  array('id' => '437', 'district_id' => '57', 'name' => 'Sundarganj', 'bangla_name' => 'সুন্দরগঞ্জ'),
  array('id' => '438', 'district_id' => '57', 'name' => 'Phulchari', 'bangla_name' => 'ফুলছড়ি'),
  array('id' => '439', 'district_id' => '58', 'name' => 'Thakurgaonsadar', 'bangla_name' => 'ঠাকুরগাঁও সদর'),
  array('id' => '440', 'district_id' => '58', 'name' => 'Pirganj', 'bangla_name' => 'পীরগঞ্জ'),
  array('id' => '441', 'district_id' => '58', 'name' => 'Ranisankail', 'bangla_name' => 'রাণীশংকৈল'),
  array('id' => '442', 'district_id' => '58', 'name' => 'Haripur', 'bangla_name' => 'হরিপুর'),
  array('id' => '443', 'district_id' => '58', 'name' => 'Baliadangi', 'bangla_name' => 'বালিয়াডাঙ্গী'),
  array('id' => '444', 'district_id' => '59', 'name' => 'Rangpursadar', 'bangla_name' => 'রংপুর সদর'),
  array('id' => '445', 'district_id' => '59', 'name' => 'Gangachara', 'bangla_name' => 'গংগাচড়া'),
  array('id' => '446', 'district_id' => '59', 'name' => 'Taragonj', 'bangla_name' => 'তারাগঞ্জ'),
  array('id' => '447', 'district_id' => '59', 'name' => 'Badargonj', 'bangla_name' => 'বদরগঞ্জ'),
  array('id' => '448', 'district_id' => '59', 'name' => 'Mithapukur', 'bangla_name' => 'মিঠাপুকুর'),
  array('id' => '449', 'district_id' => '59', 'name' => 'Pirgonj', 'bangla_name' => 'পীরগঞ্জ'),
  array('id' => '450', 'district_id' => '59', 'name' => 'Kaunia', 'bangla_name' => 'কাউনিয়া'),
  array('id' => '451', 'district_id' => '59', 'name' => 'Pirgacha', 'bangla_name' => 'পীরগাছা'),
  array('id' => '452', 'district_id' => '60', 'name' => 'Kurigramsadar', 'bangla_name' => 'কুড়িগ্রাম সদর'),
  array('id' => '453', 'district_id' => '60', 'name' => 'Nageshwari', 'bangla_name' => 'নাগেশ্বরী'),
  array('id' => '454', 'district_id' => '60', 'name' => 'Bhurungamari', 'bangla_name' => 'ভুরুঙ্গামারী'),
  array('id' => '455', 'district_id' => '60', 'name' => 'Phulbari', 'bangla_name' => 'ফুলবাড়ী'),
  array('id' => '456', 'district_id' => '60', 'name' => 'Rajarhat', 'bangla_name' => 'রাজারহাট'),
  array('id' => '457', 'district_id' => '60', 'name' => 'Ulipur', 'bangla_name' => 'উলিপুর'),
  array('id' => '458', 'district_id' => '60', 'name' => 'Chilmari', 'bangla_name' => 'চিলমারী'),
  array('id' => '459', 'district_id' => '60', 'name' => 'Rowmari', 'bangla_name' => 'রৌমারী'),
  array('id' => '460', 'district_id' => '60', 'name' => 'Charrajibpur', 'bangla_name' => 'চর রাজিবপুর'),
  array('id' => '461', 'district_id' => '61', 'name' => 'Sherpursadar', 'bangla_name' => 'শেরপুর সদর'),
  array('id' => '462', 'district_id' => '61', 'name' => 'Nalitabari', 'bangla_name' => 'নালিতাবাড়ী'),
  array('id' => '463', 'district_id' => '61', 'name' => 'Sreebordi', 'bangla_name' => 'শ্রীবরদী'),
  array('id' => '464', 'district_id' => '61', 'name' => 'Nokla', 'bangla_name' => 'নকলা'),
  array('id' => '465', 'district_id' => '61', 'name' => 'Jhenaigati', 'bangla_name' => 'ঝিনাইগাতী'),
  array('id' => '466', 'district_id' => '62', 'name' => 'Fulbaria', 'bangla_name' => 'ফুলবাড়ীয়া'),
  array('id' => '467', 'district_id' => '62', 'name' => 'Trishal', 'bangla_name' => 'ত্রিশাল'),
  array('id' => '468', 'district_id' => '62', 'name' => 'Bhaluka', 'bangla_name' => 'ভালুকা'),
  array('id' => '469', 'district_id' => '62', 'name' => 'Muktagacha', 'bangla_name' => 'মুক্তাগাছা'),
  array('id' => '470', 'district_id' => '62', 'name' => 'Mymensinghsadar', 'bangla_name' => 'ময়মনসিংহ সদর'),
  array('id' => '471', 'district_id' => '62', 'name' => 'Dhobaura', 'bangla_name' => 'ধোবাউড়া'),
  array('id' => '472', 'district_id' => '62', 'name' => 'Phulpur', 'bangla_name' => 'ফুলপুর'),
  array('id' => '473', 'district_id' => '62', 'name' => 'Haluaghat', 'bangla_name' => 'হালুয়াঘাট'),
  array('id' => '474', 'district_id' => '62', 'name' => 'Gouripur', 'bangla_name' => 'গৌরীপুর'),
  array('id' => '475', 'district_id' => '62', 'name' => 'Gafargaon', 'bangla_name' => 'গফরগাঁও'),
  array('id' => '476', 'district_id' => '62', 'name' => 'Iswarganj', 'bangla_name' => 'ঈশ্বরগঞ্জ'),
  array('id' => '477', 'district_id' => '62', 'name' => 'Nandail', 'bangla_name' => 'নান্দাইল'),
  array('id' => '478', 'district_id' => '62', 'name' => 'Tarakanda', 'bangla_name' => 'তারাকান্দা'),
  array('id' => '479', 'district_id' => '63', 'name' => 'Jamalpursadar', 'bangla_name' => 'জামালপুর সদর'),
  array('id' => '480', 'district_id' => '63', 'name' => 'Melandah', 'bangla_name' => 'মেলান্দহ'),
  array('id' => '481', 'district_id' => '63', 'name' => 'Islampur', 'bangla_name' => 'ইসলামপুর'),
  array('id' => '482', 'district_id' => '63', 'name' => 'Dewangonj', 'bangla_name' => 'দেওয়ানগঞ্জ'),
  array('id' => '483', 'district_id' => '63', 'name' => 'Sarishabari', 'bangla_name' => 'সরিষাবাড়ী'),
  array('id' => '484', 'district_id' => '63', 'name' => 'Madarganj', 'bangla_name' => 'মাদারগঞ্জ'),
  array('id' => '485', 'district_id' => '63', 'name' => 'Bokshiganj', 'bangla_name' => 'বকশীগঞ্জ'),
  array('id' => '486', 'district_id' => '64', 'name' => 'Barhatta', 'bangla_name' => 'বারহাট্টা'),
  array('id' => '487', 'district_id' => '64', 'name' => 'Durgapur', 'bangla_name' => 'দুর্গাপুর'),
  array('id' => '488', 'district_id' => '64', 'name' => 'Kendua', 'bangla_name' => 'কেন্দুয়া'),
  array('id' => '489', 'district_id' => '64', 'name' => 'Atpara', 'bangla_name' => 'আটপাড়া'),
  array('id' => '490', 'district_id' => '64', 'name' => 'Madan', 'bangla_name' => 'মদন'),
  array('id' => '491', 'district_id' => '64', 'name' => 'Khaliajuri', 'bangla_name' => 'খালিয়াজুরী'),
  array('id' => '492', 'district_id' => '64', 'name' => 'Kalmakanda', 'bangla_name' => 'কলমাকান্দা'),
  array('id' => '493', 'district_id' => '64', 'name' => 'Mohongonj', 'bangla_name' => 'মোহনগঞ্জ'),
  array('id' => '494', 'district_id' => '64', 'name' => 'Purbadhala', 'bangla_name' => 'পূর্বধলা'),
  array('id' => '495', 'district_id' => '64', 'name' => 'Netrokonasadar', 'bangla_name' => 'নেত্রকোণা সদর'),
  array('id' => '496', 'district_id' => '21', 'name' => 'Karnafuli', 'bangla_name' => 'কর্ণফুলী'),
  array('id' => '497', 'district_id' => '1', 'name' => 'Adabor', 'bangla_name' => 'আদাবর'),
  array('id' => '498', 'district_id' => '1', 'name' => 'Badda', 'bangla_name' => 'বাড্ডা'),
  array('id' => '499', 'district_id' => '1', 'name' => 'Bangshal', 'bangla_name' => 'বংশাল'),
  array('id' => '500', 'district_id' => '1', 'name' => 'Biman Bandar', 'bangla_name' => 'বিমান বন্দর'),
  array('id' => '501', 'district_id' => '1', 'name' => 'Cantonment', 'bangla_name' => 'ক্যান্টনমেন্ট'),
  array('id' => '502', 'district_id' => '1', 'name' => 'Chawkbazar', 'bangla_name' => 'চকবাজার'),
  array('id' => '503', 'district_id' => '1', 'name' => 'Dakshinkhan', 'bangla_name' => 'দক্ষিণখান'),
  array('id' => '504', 'district_id' => '1', 'name' => 'Darus Salam', 'bangla_name' => 'দার-উস-সালাম'),
  array('id' => '505', 'district_id' => '1', 'name' => 'Demra', 'bangla_name' => 'ডেমরা'),
  array('id' => '506', 'district_id' => '1', 'name' => 'Gendaria', 'bangla_name' => 'গেন্ডারিয়া'),
  array('id' => '507', 'district_id' => '1', 'name' => 'Hazaribagh', 'bangla_name' => 'হাজারীবাগ'),
  array('id' => '508', 'district_id' => '1', 'name' => 'Jatrabari', 'bangla_name' => 'যাত্রাবাড়ি'),
  array('id' => '509', 'district_id' => '1', 'name' => 'Kadamtali', 'bangla_name' => 'কদমতলী'),
  array('id' => '510', 'district_id' => '1', 'name' => 'Kafrul', 'bangla_name' => 'কাফরুল'),
  array('id' => '511', 'district_id' => '1', 'name' => 'Kalabagan', 'bangla_name' => 'কলাবাগান'),
  array('id' => '512', 'district_id' => '1', 'name' => 'Kamrangirchar', 'bangla_name' => 'কামরাঙ্গিরচর'),
  array('id' => '513', 'district_id' => '1', 'name' => 'Khilgaon', 'bangla_name' => 'খিলগাঁও'),
  array('id' => '514', 'district_id' => '1', 'name' => 'Khilkhet', 'bangla_name' => 'খিলক্ষেত'),
  array('id' => '515', 'district_id' => '1', 'name' => 'Kotwali', 'bangla_name' => 'কোতোয়ালী'),
  array('id' => '516', 'district_id' => '1', 'name' => 'Lalbagh', 'bangla_name' => 'লালবাগ'),
  array('id' => '517', 'district_id' => '1', 'name' => 'Mirpur', 'bangla_name' => 'মিরপুর'),
  array('id' => '518', 'district_id' => '1', 'name' => 'Mohammadpur', 'bangla_name' => 'মোহাম্মদপুর'),
  array('id' => '519', 'district_id' => '1', 'name' => 'Mohakhali', 'bangla_name' => 'মহাখালী'),
  array('id' => '520', 'district_id' => '1', 'name' => 'Motijheel', 'bangla_name' => 'মতিঝিল'),
  array('id' => '521', 'district_id' => '1', 'name' => 'New Market', 'bangla_name' => 'নিউমার্কেট'),
  array('id' => '522', 'district_id' => '1', 'name' => 'Pallabi', 'bangla_name' => 'পল্লবী'),
  array('id' => '523', 'district_id' => '1', 'name' => 'Paltan', 'bangla_name' => 'পল্টন'),
  array('id' => '524', 'district_id' => '1', 'name' => 'Ramna', 'bangla_name' => 'রমনা'),
  array('id' => '525', 'district_id' => '1', 'name' => 'Rampura', 'bangla_name' => 'রামপুরা'),
  array('id' => '526', 'district_id' => '1', 'name' => 'Sabujbagh', 'bangla_name' => 'সবুজবাগ'),
  array('id' => '527', 'district_id' => '1', 'name' => 'Shah Ali', 'bangla_name' => 'শাহ আলী'),
  array('id' => '528', 'district_id' => '1', 'name' => 'Shahbagh', 'bangla_name' => 'শাহবাগ'),
  array('id' => '529', 'district_id' => '1', 'name' => 'Sher-e-Bangla Nagar', 'bangla_name' => 'শেরেবাংলা নগর'),
  array('id' => '530', 'district_id' => '1', 'name' => 'Shyampur', 'bangla_name' => 'শ্যামপুর'),
  array('id' => '531', 'district_id' => '1', 'name' => 'Sutrapur', 'bangla_name' => 'সূত্রাপুর'),
  array('id' => '532', 'district_id' => '1', 'name' => 'Tejgaon', 'bangla_name' => 'তেজগাঁও'),
  array('id' => '533', 'district_id' => '1', 'name' => 'Turag', 'bangla_name' => 'তুরাগ'),
  array('id' => '534', 'district_id' => '1', 'name' => 'Uttara', 'bangla_name' => 'উত্তরা')
);
